### ISSUE TITLE
reports negative time?

### ISSUE THREAD

**Issue by kapilt** [self-actuated/actions-usage#4]
```
$ ./actions-usage --org cloud-custodian --token $GITHUB_TOKEN
...
...
Total repos: 11
Total private repos: 0
Total public repos: 11

Total workflow runs: 476
Total workflow jobs: 2945
Total usage: -2561705h8m48.854775808s (-153702309 mins)
```

**Comment by alexellis** [comment]
Hey @kapilt thanks for trying out the tool.

Everyone who's tried it so far has had realistic values, so I wonder what might be different here.

You clipped all the output, so it's going to be hard to look for problems? Perhaps you can create a gist a link it to here?

You have a lot of workflow jobs though. Is that a realistic amount? Did you see the note in the repo about rate limits?

> If your team has hundreds of repositories, or thousands of builds per month, then the tool may exit early due to exceeding the API rate-limit. In this case, we suggest you run with --days=10 and multiply the value by 3 to get a rough picture of 30-day usage.

What do you get for your rate-limit after running the tool?

```
curl -H "Authorization: token $GITHUB_TOKEN" \
  -X GET https://api.github.com/rate_limit
```

What happens if you change your -days range to 7 instead?

cc @Jasstkn who contributed the user-based support

**Comment by klemmster** [comment]
I've seen the same, running the tool within CI itself.
It does include the job it's currently running within:
```2023/03/04 22:26:10 Job: 11766947251 [2023-03-04 22:25:59 - 0001-01-01 00:00:00] (-2562047h47m16.854775808s): ```
The job is still running, so the `completed at` returns: `0001-01-01 00:00:00`, which then results in a negative sum.

I suspect the original posters busy org had a running job while executing the tool as well?

**Comment by Jasstkn** [comment]
> I've seen the same, running the tool within CI itself. It does include the job it's currently running within: `2023/03/04 22:26:10 Job: 11766947251 [2023-03-04 22:25:59 - 0001-01-01 00:00:00] (-2562047h47m16.854775808s): ` The job is still running, so the `completed at` returns: `0001-01-01 00:00:00`, which then results in a negative sum.
> 
> I suspect the original posters busy org had a running job while executing the tool as well?

I think we can filter out queued & running jobs, wdyt @alexellis?

**Comment by alexellis** [comment]
SGTM:

> I think we can filter out queued & running jobs, wdyt @alexellis?

Yes that'd be a good plan. Is 000-1-01 a const somewhere like `time.Min`?

**Comment by alexellis** [comment]
New release: https://github.com/self-actuated/actions-usage/releases/tag/v0.0.4
